# Ejecutar modelo tuberias + camiones

model modelamiento_camiones.mod;
data red_aguas_camiones.dat;

option solver gurobi;

solve;

# resultados
display CostoTotal;

# tuberias construidas
display {(i,j) in E: x[i,j] > 0.5} x[i,j];

# flujos tuberias
display {(i,j) in E: y[i,j] > 0} y[i,j];

# rutas camion activadas
display {(i,j) in ER: z[i,j] > 0.5} z[i,j];
display {(i,j) in ER: w[i,j] > 0} w[i,j];
# nodos que reciben agua por camion
display {n in P: r[n] > 0.5} r[n];